[package]
name = "actix-consumer"
version = "0.0.1"
edition = "2021"
publish = false

[build-dependencies]
stubr-build = { path = "../build", version = "0.4.14" }
stub-producer = { path = "../stub-producer" }

[dependencies]
actix-web = "4.0.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
anyhow = "1.0.55"
derive_more = "0.99.17"
itertools = "0.10.3"

[dev-dependencies]
stubr = { path = "../lib", version = "0.4.14", features = ["verify-actix", "record-actix"] }
asserhttp = { version = "0.4.0", features = ["actix"] }