[package]
name = "actix-consumer"
version = "0.0.1"
edition = "2021"
publish = false

[build-dependencies]
stubr-build = { path = "../build", version = "0.4.13" }
stub-producer = { path = "../stub-producer" }

[dependencies]
actix-web = "3.3.2"

[dev-dependencies]
stubr = { path = "../lib", version = "0.4.13", features = ["verify-actix"] }
actix-rt = "2.6.0"
asserhttp = { version = "0.2.4", features = ["actix"] }