[package]
name = "actix-consumer"
version = "0.0.1"
edition = "2018"
publish = false

[build-dependencies]
stubr-build = { path = "../build", version = "0.4.11" }
stubr-producer = { path = "../stub-producer" }

[dependencies]
actix-web = "3.3.2"

[dev-dependencies]
stubr = { path = "../lib", version = "0.4.11", features = ["verify-actix"] }
actix-rt = "2.4.0"
asserhttp = { version = "0.2.4", features = ["actix"] }