use_try_shorthand = true
use_field_init_shorthand = true
max_width = 140
newline_style = "Unix"
merge_derives = true
edition = "2021"
chain_width = 80
fn_call_width = 80
fn_params_layout = "Compressed"
match_block_trailing_comma = true