[package]
name = "stubr"
version = "0.0.1"
edition = "2018"

[dependencies]
serde_json = "1.0.60"
wiremock = "0.4.1"
anyhow = "1.0.36"
http-types = "2.9.0"
itertools = "0.9.0"
const_format = "0.2.10"
regex = "1.4.2"
async-trait = "0.1.42"
jsonpath_lib = "0.2.6"

[dependencies.tokio]
version = "0.2.24"
features = ["rt-core", "rt-util"]

[dependencies.serde]
version = "1.0.118"
features = ["derive"]

[dependencies.async-std]
version = "1.8.0"
features = ["attributes"]

[dev-dependencies]
surf = "2.1.0"
tempfile = "3.1.0"

[features]
iso = []