[package]
name = "stubr"
version = "0.0.1"
edition = "2018"

[dependencies]
serde_json = "1.0.59"
wiremock = "0.3"
anyhow = "1.0.33"
http-types = "2.6.0"
itertools = "0.9.0"

[dependencies.serde]
version = "1.0.117"
features = ["derive"]

[dependencies.async-std]
version = "1.6.5"
features = ["attributes"]

[dev-dependencies]
surf = "1.0.3"