[package]
name = "stubr"
version = "0.0.1"
edition = "2018"

[dependencies]
serde_json = "1.0.59"
wiremock = "0.4.0-alpha.2"
anyhow = "1.0.34"
http-types = "2.8.0"
itertools = "0.9.0"
const_format = "0.2.10"
regex = "1.4.2"
async-trait = "0.1.42"

[dependencies.tokio]
version = "0.2.23"
features = ["rt-core", "rt-util"]

[dependencies.serde]
version = "1.0.117"
features = ["derive"]

[dependencies.async-std]
version = "1.7.0"
features = ["attributes"]

[dev-dependencies]
surf = "2.1.0"
tempfile = "3.1.0"

[features]
iso = []