[workspace]
members = [
    "cli",
    "lib",
    "attributes",
    "build",
    "examples/stub-producer",
    "examples/stub-consumer"
]

[profile.release]
lto = true
codegen-units = 1

[profile.dev]
# improves compilation performances on macos
split-debuginfo = "unpacked"