[package]
name = "stubr"
version = "0.0.1"
edition = "2018"

[dependencies]
wiremock = "0.4.3"
anyhow = "1.0.37"
async-trait = "0.1.42"
serde_json = "1.0.61"
http-types = "2.9.0"
itertools = "0.10.0"
const_format = "0.2.11"
regex = "1.4.2"
jsonpath_lib = "0.2.6"
clap = "3.0.0-beta.2"

[dependencies.serde]
version = "1.0.121"
features = ["derive"]

[dependencies.async-std]
version = "1.8.0"
features = ["attributes"]

[dev-dependencies]
surf = "2.1.0"
tempfile = "3.2.0"
assert_cmd = "1.0.2"

[features]
iso = []