[package]
name = "actix-producer"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
actix-web = "3.3.2"

[dev-dependencies]
stubr = { path = "../lib", version = "0.4.13", features = ["verify-actix"] }
actix-rt = "2.5.0"