[package]
name = "actix-producer"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
actix-web = "4.0.1"

[dev-dependencies]
stubr = { path = "../lib", version = "0.4.14", features = ["verify-actix"] }
actix-rt = "2.7.0"