[package]
name = "stubr-cli"
version = "0.4.8"
edition = "2018"
authors = ["Beltram Maldant"]
description = "Wiremock implemented in Rust"
homepage = "https://github.com/beltram/stubr"
repository = "https://github.com/beltram/stubr"
license = "Apache-2.0"
keywords = ["cli", "mock", "test", "contract", "http"]
categories = ["command-line-utilities", "development-tools::testing"]

include = ["/src/*", "/Cargo.toml"]

[[bin]]
name = "stubr"
path = "src/main.rs"

[dependencies]
stubr = { path = "../lib", version = "0.4.8", features = ["record"] }
anyhow = "1.0.42"
directories = "3.0.2"
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
colored = "2.0.0"
humantime = "2.1.0"
tokio = { version = "1.9.0", features = ["macros", "rt-multi-thread"] }
log = "0.4.14"
simple_logger = "1.13.0"
async-std = "1.9.0"

[dev-dependencies]
surf = "2.2.0"
isahc = { version = "1.4.0", features = ["json"] }
assert_cmd = "2.0.0"
asserhttp = { version = "0.2.0", features = ["surf"] }
async-std = { version = "1.9.0", features = ["attributes"] }

[features]
default = []
cloud = ["stubr/cloud"]