apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: stubr
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: hello-stubr
              servicePort: 80