[package]
name = "stubr-attributes"
version = "0.4.9"
edition = "2018"
authors = ["Beltram Maldant"]
description = "Wiremock implemented in Rust"
homepage = "https://github.com/beltram/stubr"
repository = "https://github.com/beltram/stubr"
license = "Apache-2.0"
keywords = ["macro", "mock", "test", "contract", "http"]
categories = ["command-line-utilities", "development-tools::testing"]

include = ["/src/*", "/Cargo.toml"]

[lib]
proc-macro = true

[dependencies]
syn = "1.0.74"
quote = "1.0.8"
proc-macro2 = "1.0.28"

[dev-dependencies]
asserhttp = "0.2.1"
isahc = "1.5.0"
async-std = "1.9.0"