[package]
name = "stubr-attributes"
version = "0.4.11"
edition = "2021"
authors = ["Beltram Maldant"]
description = "Wiremock implemented in Rust"
homepage = "https://github.com/beltram/stubr"
repository = "https://github.com/beltram/stubr"
license = "Apache-2.0"
keywords = ["macro", "mock", "test", "contract", "http"]
categories = ["command-line-utilities", "development-tools::testing"]

include = ["/src/*", "/Cargo.toml"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.82", features = ["full"] }
quote = "1.0.10"
proc-macro2 = "1.0.34"
itertools = "0.10.3"

[dev-dependencies]
isahc = "1.6.0"
async-std = "1.10.0"
asserhttp = "0.2.4"