apiVersion: v2
name: stubr
description: stubr Helm chart
type: application
version: 0.2.0
kubeVersion: ">= 1.18.0"
appVersion: "0.3.4"
home: https://github.com/beltram/stubr
keywords:
  - wiremock
  - mock
  - stub
sources:
  - https://beltram.github.io/stubr/
  - https://github.com/beltram/stubr