replicaCount: 1

stubs: "stubs/**"

image:
  repository: ghcr.io/beltram/stubr
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true

liveness:
  failureThreshold: 1
  periodSeconds: 5
  timeoutSeconds: 1
readiness:
  failureThreshold: 1
  periodSeconds: 10
  timeoutSeconds: 1
  initialDelaySeconds: 1