apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stubr.fullname" . }}
  labels:
    {{- include "stubr.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "stubr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "stubr.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "/stubs"
            - "--port=80"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /stubs
              name: {{ include "stubr.fullname" . }}
          livenessProbe:
            httpGet:
              port: http
              path: /healtz
            failureThreshold: {{ .Values.liveness.failureThreshold }}
            periodSeconds: {{ .Values.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.liveness.timeoutSeconds }}
          readinessProbe:
            httpGet:
              port: http
              path: /healtz
            failureThreshold: {{ .Values.readiness.failureThreshold }}
            periodSeconds: {{ .Values.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.readiness.timeoutSeconds }}
            initialDelaySeconds: {{ .Values.readiness.initialDelaySeconds }}
      volumes:
        - name: {{ include "stubr.fullname" . }}
          configMap:
            name: {{ include "stubr.fullname" . }}
