[package]
name = "stubr-consumer"
version = "0.0.1"
edition = "2018"
publish = false
build = "build.rs"

[build-dependencies]
stubr-build = { path = "../build", version = "0.4.10" }
stubr-producer = { path = "../stub-producer" }
actix-producer = { path = "../actix-producer" }

[dev-dependencies]
stubr = { path = "../lib", version = "0.4.10", features = ["attributes"] }
asserhttp = { version = "0.2.3", features = ["isahc"] }
isahc = "1.6.0"
async-std = { version = "1.10.0", features = ["attributes"] }
