[package]
name = "stubr-consumer"
version = "0.0.1"
edition = "2018"
publish = false
build = "build.rs"

[build-dependencies]
stubr-build = { path = "../build", version = "0.4.7" }
stubr-producer = { path = "../stub-producer" }

[dev-dependencies]
stubr = { path = "../lib", version = "0.4.7" }
asserhttp = { version = "0.2.0", features = ["isahc"] }
isahc = "1.4.0"
async-std = { version = "1.9.0", features = ["attributes"] }