name: book

on: [ push ]

defaults:
  run:
    working-directory: book

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
           mdbook-version: 'latest'
      - run: mdbook test
      - uses: actions-rs/install@v0.1
        with:
          crate: mdbook-linkcheck
          version: latest
      - run: mdbook build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
#        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book