name: Rust-static-build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always
  BUILD_TARGET: x86_64-unknown-linux-musl
  BINARY_NAME: stubr
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            from-file: target/x86_64-unknown-linux-musl/release/stubr
            args: --best --lzma
            strip: true
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Build-musl
      uses: gmiam/rust-musl-action@master
      with:
        args: cargo build --target $BUILD_TARGET --release
    - name: upx
      uses: svenstaro/upx-action@v2
      with:
        file: ${{ matrix.from-file }}
        args: ${{ matrix.args }}
        strip: ${{ matrix.strip }}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.BINARY_NAME }}
        path: target/x86_64-unknown-linux-musl/release/${{ env.BINARY_NAME }}*
