name: helm

on:
  push:
    branches:
      - main

jobs:
  helm-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: install helm
        uses: azure/setup-helm@v3.3
        with:
          version: v3.5.3
      - name: release chart
        uses: helm/chart-releaser-action@v1.4.1
        continue-on-error: true
        with:
          charts_dir: "charts"
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}